version: 2.1
jobs:
  deploy: 
    docker: 
      - image: danish9966/aws-cdk:0.2.1
    steps:
      - checkout
      - run: echo $AWS_ACCESS_KEY_ID
      - run: pwd
      - run: ls -la
      - run: cdk --version
      - run: cd src
      - run: pwd
      - run: 
          command: pip install -r requirements.txt
          working_directory: src
      - run: 
          command: cdk deploy
          working_directory: src
  destroy:
    docker:
      - image: danish9966/aws-cdk:0.2.1
    steps:
      - checkout
      - run: 
          command: pip install -r requirements.txt
          working_directory: src
      - run:
          command: cdk destroy
          working_directory: src
workflows:
  cdk-deploy:
    jobs:
      - deploy:
          context: AWS_CREDENTIALS
          filters:
            branches:
              only:
                - master
                - develop
      - destroy:
          context: AWS_CREDENTIALS
          requires:
            - deploy
          filters:
            branches:
              only:
                - develop