version: 2.1
jobs:
  deploy: 
    docker: 
      - image: danish9966/aws-cdk:1.28.0
    steps:
      - checkout
      - run: 
          command: pip install -r requirements.txt
          working_directory: code
      - run: 
          command: cdk deploy --require-approval never
          working_directory: code

workflows:
  cdk-deploy:
    jobs:
      - deploy:
          context: AWS_CREDENTIALS
          filters:
            branches:
              only:
                - master
                - develop